workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "ARStreamer.xcodeproj"
        XCODE_SCHEME: "ARStreamer"
    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ARStreamer.xcarchive \
            -allowProvisioningUpdates
          
          xcodebuild -exportArchive \
            -archivePath build/ARStreamer.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
