workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ARStreamer.xcodeproj"  # или .xcodeproj
        XCODE_SCHEME: "ARStreamer"
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/YourApp.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
          
          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
